### ISSUE TITLE
Robot Scara

### ISSUE THREAD

**Issue by FedericoCorso** [FedericoCorso/homework1#1]
@DavidLeoni

Robot Scara
Il meccanismo scelto è il seguente, per ora ho definito i seguenti parametri:
- "s" -> spessore delle braccia
- "q1","q2" sono gli angoli descritti dalle braccia
- "l" -> la lunghezza delle braccia
![image](https://user-images.githubusercontent.com/61889240/115850019-c3c2c980-a425-11eb-92cf-1d5337dcef14.png)

**Comment by FedericoCorso** [comment]
e anche il diametro "d" delle coppie rotoidali

**Comment by DavidLeoni** [comment]
che vincoli ci sono tra le due braccia? (i.e. il secondo braccio non può essere più lungo del primo?)

**Comment by FedericoCorso** [comment]
Io volevo imporre che le braccia dovessero avere la stessa lunghezza

**Comment by DavidLeoni** [comment]
ho visto dopo, è tanto per capire che vnicoli risulterebbero oltre a valori non negativi, tipo immagino i diametri delle coppie non debbano superare le dimensioni delle braccia, poi?

**Comment by FedericoCorso** [comment]
si esatto, ho scritto i possibili vincoli che mi sono venuti in mente nel file README, poi ci sarebbe il fatto di avere spessori delle braccia uguali, il valore dell'angolo del secondo braccio rispetto al primo non deve essere nullo inoltre le dimensioni devono essere strettamente positive, questi erano i vincoli che mi sono venuti in mente. Possono bastare?

**Comment by DavidLeoni** [comment]
Magari aggiungi anche la distanza delle joint dai bordi
