### ISSUE TITLE
Integrating piston device

### ISSUE THREAD

**Issue by FedericoCorso** [FedericoCorso/homework1#14]
@lucabeber uso il codice relativo al pistone per creare una machine insieme al mio sacra robot

**Comment by DavidLeoni** [comment]
@lucabeber ha usato il tuo device per fare una machine e tu usi il suo device per fare una machine. Spero siano sufficientemente diverse...

**Comment by FedericoCorso** [comment]
> @lucabeber ha usato il tuo device per fare una machine e tu usi il suo device per fare una machine. Spero siano sufficientemente diverse...

Buongiorno, si abbiamo collaborato ma io realizzo un meccanismo a pantografo mentre @lucabeber realizza un pistone del tipo biella-manovella.
