### ISSUE TITLE
chiamata di funzione 

### ISSUE THREAD

**Issue by lucabeber** [FedericoCorso/homework1#15]
quando chiami la funzione sc_scara_init richiami una serie di parmametri ma poi li ridefinisci all'interno della funzione. Se vuoi far immettere i parametri all'interno della funzione non ha senso che ci siano anche quando richiami la funzione, puoi benissimo richiamare una funzione vuota.

**Comment by FedericoCorso** [comment]
Ok grazie, eh infatti non ero tanto convinto di quella cosa, più che altro la ho fatta solo per avere un main un po' più pulito altrimenti dovevo per ogni if scrivere il comando in cui chiedo i parametri. Ora la sistemo.

**Comment by FedericoCorso** [comment]
Alternativamente tu dici che potrei chiamare la funzione senza parametri in input e definire al suo interno le variabili che mi servono?

**Comment by lucabeber** [comment]
> Alternativamente tu dici che potrei chiamare la funzione senza parametri in input e definire al suo interno le variabili che mi servono?

si esatto
